export const buttons = [
  { id: 1, buttonTextValue: "7" },
  { id: 2, buttonTextValue: "8" },
  { id: 3, buttonTextValue: "9" },
  { id: 4, buttonTextValue: "4" },
  { id: 5, buttonTextValue: "5" },
  { id: 6, buttonTextValue: "6" },
  { id: 7, buttonTextValue: "1" },
  { id: 8, buttonTextValue: "2" },
  { id: 9, buttonTextValue: "3" },
  { id: 10, buttonTextValue: "0" },
  { id: 11, buttonTextValue: "." },
  { id: 12, buttonTextValue: "%", div: () => {} },
  { id: 13, buttonTextValue: "x", mult: () => {} },
  { id: 14, buttonTextValue: "-", sub: () => {} },
  { id: 15, buttonTextValue: "+", sum: () => {} },
  { id: 16, buttonTextValue: "=", result: () => {} },
  { id: 17, buttonTextValue: "AC", fullClear: () => {} },
  { id: 18, buttonTextValue: "<=", clear: () => {} },
]